apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpointslice-updater-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: new-service-account
  namespace: default
roleRef:
  kind: Role
  name: endpointslice-updater
  apiGroup: rbac.authorization.k8s.io
